### PR TITLE
Added shapes object to message and flow with node shapes.

### PR DESCRIPTION
**Pull request by devleaks**
As discussed in "Issue".
Pierre

### CODE REVIEW

**Comment by hardillb** [comment]
Function looks ok at first glance, but can you fix the indenting to use spaces not tabs so it matches the original code please then I'll look at merging it.

Also the issue in question is #2

**Comment by devleaks** [comment]
ok, I converted tabs to spaces.
Pierre

**Comment by hardillb** [comment]
OK, I've had chance to have a proper look at this now.

1. I said I didn't want to pollute the context with shapes, they should only be added to the messages as they travel down the flow.

2. The shapes object should be under the msg.location object not in the root of the msg object

3. You never actually add the shapes object to the msg object if it doesn't exist, line [129](https://github.com/hardillb/node-red-node-geofence/pull/3/files#diff-0e82cae33945075d475e0c28c4cd0466R129) should be:
    `msg.locations.shapes = msg.locations.shapes || {};`

**Comment by hardillb** [comment]
The README.md will need updating to reflect the code you just removed (but also see the comment I just made on the issue)

**Comment by devleaks** [comment]
Readme was updated and should be in phase with code. What’s wrong?
P.

**Comment by hardillb** [comment]
I'm going to close this unless you're going to make the changes to allow the flow variable name to be changed as mentioned in the issue #2

**Comment by devleaks** [comment]
Yep, you can close this.
Pierre

**Pull request closed without merging**
